package tester;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BiddingDashboardService service = new BiddingDashboardService();
 * BiddingDashboardServicePortType portType = service.getBiddingDashboardServiceHttpPort();
 * portType.sendTestEvent(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BiddingDashboardService", targetNamespace = "http://webservice.wrv.fcc.gov", wsdlLocation = "http://localhost:7777/wrv/services/DashboardService?wsdl")
public class BiddingDashboardService extends Service {

	private final static URL BIDDINGDASHBOARDSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(tester.BiddingDashboardService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = tester.BiddingDashboardService.class.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:7777/wrv/services/DashboardService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:7777/wrv/services/DashboardService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BIDDINGDASHBOARDSERVICE_WSDL_LOCATION = url;
	}

	public BiddingDashboardService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BiddingDashboardService() {
		super(BIDDINGDASHBOARDSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.wrv.fcc.gov", "BiddingDashboardService"));
	}

	/**
	 * 
	 * @return returns BiddingDashboardServicePortType
	 */
	@WebEndpoint(name = "BiddingDashboardServiceHttpPort")
	public BiddingDashboardServicePortType getBiddingDashboardServiceHttpPort() {
		return super.getPort(new QName("http://webservice.wrv.fcc.gov",
				"BiddingDashboardServiceHttpPort"),
				BiddingDashboardServicePortType.class);
	}

}
