package tester;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BiddingDashboardServicePortType", targetNamespace = "http://webservice.wrv.fcc.gov")
public interface BiddingDashboardServicePortType {

	/**
	 * 
	 * @param in0
	 */
	@WebMethod
	@RequestWrapper(localName = "sendTestEvent", targetNamespace = "http://webservice.wrv.fcc.gov", className = "tester.SendTestEvent")
	@ResponseWrapper(localName = "sendTestEventResponse", targetNamespace = "http://webservice.wrv.fcc.gov", className = "tester.SendTestEventResponse")
	public void sendTestEvent(
			@WebParam(name = "in0", targetNamespace = "http://webservice.wrv.fcc.gov") WrvEvent in0);

	/**
	 * 
	 * @param in0
	 */
	@WebMethod
	@RequestWrapper(localName = "sendEvent", targetNamespace = "http://webservice.wrv.fcc.gov", className = "tester.SendEvent")
	@ResponseWrapper(localName = "sendEventResponse", targetNamespace = "http://webservice.wrv.fcc.gov", className = "tester.SendEventResponse")
	public void sendEvent(
			@WebParam(name = "in0", targetNamespace = "http://webservice.wrv.fcc.gov") WrvEvent in0);

	/**
     * 
     */
	@WebMethod
	@RequestWrapper(localName = "verifyWS", targetNamespace = "http://webservice.wrv.fcc.gov", className = "tester.VerifyWS")
	@ResponseWrapper(localName = "verifyWSResponse", targetNamespace = "http://webservice.wrv.fcc.gov", className = "tester.VerifyWSResponse")
	public void verifyWS();

}
